language: node_js
node_js:
- 12

before_deploy:
- npm run build:prod

deploy:
- provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: https://snake.inker.one
  on:
    branch: master
